table Global
	lineageTag: 50865a9b-6cf8-4099-8c78-4c4726a438ec

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 21dbc71e-2b00-4f50-9a53-e2ad995f89b0
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Station
		dataType: string
		lineageTag: ebaaa606-bf97-4fd9-958a-f8578265326c
		dataCategory: City
		summarizeBy: none
		sourceColumn: Station

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		lineageTag: 1075bf94-86a5-490b-aa82-61c6389eb3ab
		dataCategory: Country
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	partition Global = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\marib\OneDrive\Desktop\Power_BI_AIR\Global_Air_Quality.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID", Int64.Type}, {"Station", type text}, {"County", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

